### Open Flights Data Wrangling

To practice, you are going to wrangle data from OpenFlights.  You can read about it here: 

http://openflights.org/data.html

This includes three main files, one for each airport, one for each airline, and one for each route.  They can be merged or joined with the appropriate fields.  I have modified the files slightly to include a header row in the .dat files, which makes it a bit easier for you.  

You are required to work through the problems below.  This may take some time.  Be persistent, and ask questions or seek help as needed.

In [87]:
import pandas as pd
import numpy as np

In [88]:
# These files use \N as a missing value indicator.  When reading the CSVs, we will tell
# it to use that value as missing or NA.  The double backslash is required because
# otherwise it will interpret \N as a carriage return. 

# Read in the airports data.
airports = pd.read_csv("data/airports.dat", header=None, na_values='\\N')
airports.columns = ["id", "name", "city", "country", "iata", "icao", "latitude", "longitude", "altitude","timezone", "dst", "tz", "type", "source"]

# Read in the airlines data.
airlines = pd.read_csv("data/airlines.dat", header=None, na_values='\\N')
airlines.columns = ["id", "name", "alias", "iata", "icao", "callsign", "country", "active"]

# Read in the routes data.
routes = pd.read_csv("data/routes.dat", header=None, na_values='\\N')
routes.columns = ["airline", "airline_id", "source", "source_id", "dest", "dest_id", "codeshare", "stops", "equipment"]

1) Start by seeing what's in the data.  What columns are there?  What data types are the columns?  

Remember, 'object' means it is a string, while the numerical values can be floats or ints.  Sometimes you will have problems if it reads numeric data in as strings.  If that happens, you can use the function .astype() to convert it.  Look it up in the pandas API to get more details

In [89]:
airports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7184 entries, 0 to 7183
Data columns (total 14 columns):
id           7184 non-null int64
name         7184 non-null object
city         7140 non-null object
country      7184 non-null object
iata         5652 non-null object
icao         7184 non-null object
latitude     7184 non-null float64
longitude    7184 non-null float64
altitude     7184 non-null int64
timezone     6874 non-null float64
dst          6874 non-null object
tz           6591 non-null object
type         7184 non-null object
source       7184 non-null object
dtypes: float64(3), int64(2), object(9)
memory usage: 785.8+ KB

In [90]:
airports.head()

,id,name,city,country,iata,icao,latitude,longitude,altitude,timezone,dst,tz,type,source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10.0,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10.0,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10.0,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10.0,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10.0,U,Pacific/Port_Moresby,airport,OurAirports

In [91]:
airlines.head()

,id,name,alias,iata,icao,callsign,country,active
0,-1,Unknown,NaN,-,NaN,NaN,NaN,Y
1,1,Private flight,NaN,-,NaN,NaN,NaN,Y
2,2,135 Airways,NaN,NaN,GNL,GENERAL,United States,N
3,3,1Time Airline,NaN,1T,RNX,NEXTIME,South Africa,Y
4,4,2 Sqn No 1 Elementary Flying Training School,NaN,NaN,WYT,NaN,United Kingdom,N

routes.head()

In [92]:
routes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67663 entries, 0 to 67662
Data columns (total 9 columns):
airline       67663 non-null object
airline_id    67184 non-null float64
source        67663 non-null object
source_id     67443 non-null float64
dest          67663 non-null object
dest_id       67442 non-null float64
codeshare     14597 non-null object
stops         67663 non-null int64
equipment     67645 non-null object
dtypes: float64(3), int64(1), object(5)
memory usage: 4.6+ MB

2) Select just the routes that go to or from Lexington Bluegrass Airport, and store them in their own dataframe.  

The airport code is LEX.  You should have a much smaller dataframe.  How many inbound routes and how many outbound routes are there?

In [93]:
r1=routes[routes['source'].str.contains('LEX')]
df_r1 = pd.DataFrame(r1)
r2=routes[routes['dest'].str.contains('LEX')]
df_r2 = pd.DataFrame(r2)
df_r3 = pd.concat([df_r1, df_r2])
df_r3

,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment
3588,9E,3976.0,LEX,4017.0,ATL,3682.0,NaN,0,CRJ
5763,AA,24.0,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ
5764,AA,24.0,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4
5765,AA,24.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4
9641,AF,137.0,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9
21095,DL,2009.0,LEX,4017.0,ATL,3682.0,NaN,0,M88 717
21096,DL,2009.0,LEX,4017.0,DCA,3520.0,Y,0,CRJ
21097,DL,2009.0,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9
21098,DL,2009.0,LEX,4017.0,LGA,3697.0,NaN,0,ERJ
21099,DL,2009.0,LEX,4017.0,MSP,3858.0,Y,0,CRJ
29047,G4,35.0,LEX,4017.0,FLL,3533.0,NaN,0,M80
29048,G4,35.0,LEX,4017.0,PGD,7056.0,NaN,0,M80
29049,G4,35.0,LEX,4017.0,PIE,3617.0,NaN,0,320
29050,G4,35.0,LEX,4017.0,SFB,4167.0,NaN,0,M80 320
36746,KL,3090.0,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ
57029,UA,5209.0,LEX,4017.0,IAH,3550.0,Y,0,ERJ
57030,UA,5209.0,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ
59544,US,5265.0,LEX,4017.0,CLT,3876.0,NaN,0,CR7
59545,US,5265.0,LEX,4017.0,DFW,3670.0,NaN,0,ERD
59546,US,5265.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4
3569,9E,3976.0,ATL,3682.0,LEX,4017.0,NaN,0,CRJ
4953,AA,24.0,CLT,3876.0,LEX,4017.0,NaN,0,CR7
5247,AA,24.0,DFW,3670.0,LEX,4017.0,Y,0,ERD ER4
6283,AA,24.0,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4
9097,AF,137.0,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ 717
20164,DL,2009.0,ATL,3682.0,LEX,4017.0,NaN,0,M88 717
20534,DL,2009.0,DCA,3520.0,LEX,4017.0,Y,0,CRJ
20638,DL,2009.0,DTW,3645.0,LEX,4017.0,NaN,0,717
21131,DL,2009.0,LGA,3697.0,LEX,4017.0,Y,0,ERJ
21402,DL,2009.0,MSP,3858.0,LEX,4017.0,Y,0,CRJ
28951,G4,35.0,FLL,3533.0,LEX,4017.0,NaN,0,M80
29090,G4,35.0,PGD,7056.0,LEX,4017.0,NaN,0,M80
29120,G4,35.0,PIE,3617.0,LEX,4017.0,NaN,0,320
29187,G4,35.0,SFB,4167.0,LEX,4017.0,NaN,0,M80 320
36396,KL,3090.0,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ
56775,UA,5209.0,IAH,3550.0,LEX,4017.0,Y,0,ERJ
57322,UA,5209.0,ORD,3830.0,LEX,4017.0,Y,0,ERJ CRJ
58812,US,5265.0,CLT,3876.0,LEX,4017.0,NaN,0,CR7
59096,US,5265.0,DFW,3670.0,LEX,4017.0,NaN,0,ERD
59924,US,5265.0,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4

In [94]:
#outbond
dep_lex = df_r3[df_r3['source'] == 'LEX']
print ("the number of LEX departures is", len(dep_lex))

the number of LEX departures is 20

In [95]:
#inbound
arr_lex = df_r3[df_r3['dest'] =='LEX']
print ("the number of LEX arrivals is", len(arr_lex))

the number of LEX arrivals is 20

3) Now let's look at which airlines operate in and out of Lexington.  To do this, you need to merge the airline dataframe to the route dataframe.  

How many routes does each airline have?  The value_counts() method may be useful for answering this question.

In [96]:
df_4 = pd.merge(df_r3, airlines, how= 'left', left_on ='airline_id', right_on='id')
df_4

,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment,id,name,alias,iata,icao,callsign,country,active
0,9E,3976,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y
1,AA,24,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
2,AA,24,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
3,AA,24,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
4,AF,137,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y
5,DL,2009,LEX,4017.0,ATL,3682.0,NaN,0,M88 717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
6,DL,2009,LEX,4017.0,DCA,3520.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
7,DL,2009,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
8,DL,2009,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
9,DL,2009,LEX,4017.0,MSP,3858.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
10,G4,35,LEX,4017.0,FLL,3533.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
11,G4,35,LEX,4017.0,PGD,7056.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
12,G4,35,LEX,4017.0,PIE,3617.0,NaN,0,320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
13,G4,35,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
14,KL,3090,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y
15,UA,5209,LEX,4017.0,IAH,3550.0,Y,0,ERJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y
16,UA,5209,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y
17,US,5265,LEX,4017.0,CLT,3876.0,NaN,0,CR7,5265,US Airways,NaN,US,USA,U S AIR,United States,Y
18,US,5265,LEX,4017.0,DFW,3670.0,NaN,0,ERD,5265,US Airways,NaN,US,USA,U S AIR,United States,Y
19,US,5265,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,5265,US Airways,NaN,US,USA,U S AIR,United States,Y
20,9E,3976,ATL,3682.0,LEX,4017.0,NaN,0,CRJ,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y
21,AA,24,CLT,3876.0,LEX,4017.0,NaN,0,CR7,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
22,AA,24,DFW,3670.0,LEX,4017.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
23,AA,24,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
24,AF,137,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ 717,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y
25,DL,2009,ATL,3682.0,LEX,4017.0,NaN,0,M88 717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
26,DL,2009,DCA,3520.0,LEX,4017.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
27,DL,2009,DTW,3645.0,LEX,4017.0,NaN,0,717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
28,DL,2009,LGA,3697.0,LEX,4017.0,Y,0,ERJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
29,DL,2009,MSP,3858.0,LEX,4017.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
30,G4,35,FLL,3533.0,LEX,4017.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
31,G4,35,PGD,7056.0,LEX,4017.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
32,G4,35,PIE,3617.0,LEX,4017.0,NaN,0,320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
33,G4,35,SFB,4167.0,LEX,4017.0,NaN,0,M80 320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
34,KL,3090,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y
35,UA,5209,IAH,3550.0,LEX,4017.0,Y,0,ERJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y
36,UA,5209,ORD,3830.0,LEX,4017.0,Y,0,ERJ CRJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y
37,US,5265,CLT,3876.0,LEX,4017.0,NaN,0,CR7,5265,US Airways,NaN,US,USA,U S AIR,United States,Y
38,US,5265,DFW,3670.0,LEX,4017.0,NaN,0,ERD,5265,US Airways,NaN,US,USA,U S AIR,United States,Y
39,US,5265,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4,5265,US Airways,NaN,US,USA,U S AIR,United States,Y

In [97]:
df_4['name'].value_counts()

Delta Air Lines             10
Allegiant Air                8
US Airways                   6
American Airlines            6
United Airlines              4
Air France                   2
KLM Royal Dutch Airlines     2
Pinnacle Airlines            2
Name: name, dtype: int64

4) It looks like there are some international airlines with Lexington routes.  To look at how many routes they have, create a new column in your dataframe called 'International', which is set to Y for an overseas airline and N for a domestic airline.  Calculate the percent of routes with an overseas airline.

In [98]:
df_4['international']=np.where(df_4['country'] != 'United States','Y','N')
df_4

,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment,id,name,alias,iata,icao,callsign,country,active,international
0,9E,3976,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y,N
1,AA,24,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
2,AA,24,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
3,AA,24,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
4,AF,137,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y,Y
5,DL,2009,LEX,4017.0,ATL,3682.0,NaN,0,M88 717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
6,DL,2009,LEX,4017.0,DCA,3520.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
7,DL,2009,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
8,DL,2009,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
9,DL,2009,LEX,4017.0,MSP,3858.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
10,G4,35,LEX,4017.0,FLL,3533.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
11,G4,35,LEX,4017.0,PGD,7056.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
12,G4,35,LEX,4017.0,PIE,3617.0,NaN,0,320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
13,G4,35,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
14,KL,3090,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y,Y
15,UA,5209,LEX,4017.0,IAH,3550.0,Y,0,ERJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
16,UA,5209,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
17,US,5265,LEX,4017.0,CLT,3876.0,NaN,0,CR7,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
18,US,5265,LEX,4017.0,DFW,3670.0,NaN,0,ERD,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
19,US,5265,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
20,9E,3976,ATL,3682.0,LEX,4017.0,NaN,0,CRJ,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y,N
21,AA,24,CLT,3876.0,LEX,4017.0,NaN,0,CR7,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
22,AA,24,DFW,3670.0,LEX,4017.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
23,AA,24,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
24,AF,137,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ 717,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y,Y
25,DL,2009,ATL,3682.0,LEX,4017.0,NaN,0,M88 717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
26,DL,2009,DCA,3520.0,LEX,4017.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
27,DL,2009,DTW,3645.0,LEX,4017.0,NaN,0,717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
28,DL,2009,LGA,3697.0,LEX,4017.0,Y,0,ERJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
29,DL,2009,MSP,3858.0,LEX,4017.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
30,G4,35,FLL,3533.0,LEX,4017.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
31,G4,35,PGD,7056.0,LEX,4017.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
32,G4,35,PIE,3617.0,LEX,4017.0,NaN,0,320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
33,G4,35,SFB,4167.0,LEX,4017.0,NaN,0,M80 320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
34,KL,3090,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y,Y
35,UA,5209,IAH,3550.0,LEX,4017.0,Y,0,ERJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
36,UA,5209,ORD,3830.0,LEX,4017.0,Y,0,ERJ CRJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
37,US,5265,CLT,3876.0,LEX,4017.0,NaN,0,CR7,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
38,US,5265,DFW,3670.0,LEX,4017.0,NaN,0,ERD,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
39,US,5265,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N

In [99]:
inter = df_4[df_4['international']=='Y']
inter = len(inter)
nat = df_4[df_4['international']=='N']
nat = len(nat)
#percent of international flights in or out of Lexington
per_int = inter/(nat + inter)*100
print ("international flights are", per_int,"%")

international flights are 10.0 %

5) Actually, it looks like a bunch of these routes are codeshares.  That means they are marketed by this airline, but operated by a different airline.  See the note in the data documentation on openflights.org/data.  The implication of this is that there are duplicates.

Can you figure out which ones are duplicates?  Can you then create a dataframe with only the unique routes?  How many unique inbound and outbound routes are there? 

Remember, someone has to operate the flight, so if all the routes to/from a particular airport are listed as codeshares, then something is funny...

It is also possible that more than one airline actually operates a route between the same two airports. (Having this sort of competition generally means that you will get better fares as a traveler.)  It may not be obvious what is actually in the data set, so dig or do external research as needed.

In [102]:
df_4.sort_values(by =['source', 'dest', 'codeshare'])

,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment,id,name,alias,iata,icao,callsign,country,active,international
24,AF,137,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ 717,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y,Y
34,KL,3090,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y,Y
20,9E,3976,ATL,3682.0,LEX,4017.0,NaN,0,CRJ,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y,N
25,DL,2009,ATL,3682.0,LEX,4017.0,NaN,0,M88 717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
21,AA,24,CLT,3876.0,LEX,4017.0,NaN,0,CR7,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
37,US,5265,CLT,3876.0,LEX,4017.0,NaN,0,CR7,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
26,DL,2009,DCA,3520.0,LEX,4017.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
22,AA,24,DFW,3670.0,LEX,4017.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
38,US,5265,DFW,3670.0,LEX,4017.0,NaN,0,ERD,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
27,DL,2009,DTW,3645.0,LEX,4017.0,NaN,0,717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
30,G4,35,FLL,3533.0,LEX,4017.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
35,UA,5209,IAH,3550.0,LEX,4017.0,Y,0,ERJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
4,AF,137,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y,Y
14,KL,3090,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y,Y
0,9E,3976,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y,N
5,DL,2009,LEX,4017.0,ATL,3682.0,NaN,0,M88 717,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
1,AA,24,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
17,US,5265,LEX,4017.0,CLT,3876.0,NaN,0,CR7,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
6,DL,2009,LEX,4017.0,DCA,3520.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
2,AA,24,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
18,US,5265,LEX,4017.0,DFW,3670.0,NaN,0,ERD,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
7,DL,2009,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
10,G4,35,LEX,4017.0,FLL,3533.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
15,UA,5209,LEX,4017.0,IAH,3550.0,Y,0,ERJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
8,DL,2009,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
9,DL,2009,LEX,4017.0,MSP,3858.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
3,AA,24,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
16,UA,5209,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
19,US,5265,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
11,G4,35,LEX,4017.0,PGD,7056.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
12,G4,35,LEX,4017.0,PIE,3617.0,NaN,0,320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
13,G4,35,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
28,DL,2009,LGA,3697.0,LEX,4017.0,Y,0,ERJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
29,DL,2009,MSP,3858.0,LEX,4017.0,Y,0,CRJ,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,N
23,AA,24,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,N
36,UA,5209,ORD,3830.0,LEX,4017.0,Y,0,ERJ CRJ,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,N
39,US,5265,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,N
31,G4,35,PGD,7056.0,LEX,4017.0,NaN,0,M80,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
32,G4,35,PIE,3617.0,LEX,4017.0,NaN,0,320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N
33,G4,35,SFB,4167.0,LEX,4017.0,NaN,0,M80 320,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,N

In [117]:
if df_4['source']=='Y'
    df_5 = df_4.drop_duplicates(subset = ['source']&['dest'])
    df_5.sort_values(by=['source', 'dest', 'codeshare'])

SyntaxError: invalid syntax (<ipython-input-117-f38fb0e4f4e4>, line 1)